TR ::= (0,0) ; L,T1 | (0,0) ; V,;L,T2 | (0,0) ; V,;V,;L,T3
T1 ::= (0,0) ; L | (0,0) ; V,T1
T2 ::= (0,1) ; V;L | (0,1) ; V,;V,T2
T3 ::= (0,2) ; V;V;L | (0,2) ; V,;V,;V,T3
L ::= (0,0) ; V;L | (0,0) ; V
V ::= (0,0) ; avsin | (0,0) ; ahsin | (0,0) ; asin | (0,0) ; acos | (0,0) ; h | (0,0) ; s
