TR ::= (0,0) ; T1L | (0,0) ; T2L | (0,0) ; T3L
T1L ::= (0,0) ; L,T1C
T1C ::= (0,0) ; V,T1C | (0,0) ; L
T2L ::= (0,1) ; V,;L,T2C
T2C ::= (0,1) ; V,;V,T2C | (0,1) ; V;L
T3L ::= (0,2) ; V,;V,;L,T3C
T3C ::= (0,2) ; V,;V,;V,T3C | (0,2) ; V;V;L
L ::= (0,0) ; V;L | (0,0) ; V
V ::= (0,0) ; avsin | (0,0) ; ahsin | (0,0) ; h | (0,0) ; s